reconnect_client:
  name: Reconnect Client
  description: Force a client to reconnect to the network.
  fields:
    mac:
      name: MAC Address
      description: MAC address of the client to reconnect.
      required: true
      selector:
        text:

remove_clients:
  name: Remove Offline Clients
  description: Remove all offline clients from the UniFi controller.

block_client:
  name: Block Client
  description: Block a client from the network.
  fields:
    mac:
      name: MAC Address
      description: MAC address of the client to block.
      required: true
      selector:
        text:

unblock_client:
  name: Unblock Client
  description: Unblock a client on the network.
  fields:
    mac:
      name: MAC Address
      description: MAC address of the client to unblock.
      required: true
      selector:
        text:

kick_client:
  name: Kick Client
  description: Disconnect a client from the network (they can reconnect).
  fields:
    mac:
      name: MAC Address
      description: MAC address of the client to disconnect.
      required: true
      selector:
        text:

forget_client:
  name: Forget Client
  description: Remove a client from the known clients list on the controller.
  fields:
    mac:
      name: MAC Address
      description: MAC address of the client to forget.
      required: true
      selector:
        text:
